version: "3"
services:
  app:
    container_name: chuguev_docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes:
      - .:/var/www/html
    links:
      - mysql
  mysql:
    image: mysql:5.7.28
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=chuguev_docker_test
  phpmyadmin:
    container_name: chuguev_phpmyadmin
    image: phpmyadmin/phpmyadmin:4.9.1
    ports:
      - 8082:80
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=chuguev_docker_test
      - PMA_HOST=mysql
    links:
      - mysql
